AA_PREFIX = "aleph-alpha/"

MODEL_GEMMA = f"{AA_PREFIX}gemma-3-27b-it"
MODEL_LLAMA = f"{AA_PREFIX}llama-3.3-70b-instruct"
MODEL_GPT_OSS_120B = f"{AA_PREFIX}gpt-oss-120b"
MODEL_QWEN3_30B_A3B_THINKING_2507_FP8 = f"{AA_PREFIX}qwen3-30b-a3b-thinking-2507-fp8"
MODEL_QWEN3_235B_A22B_THINKING_2507_FP8 = (
    f"{AA_PREFIX}qwen3-235b-a22b-thinking-2507-fp8"
)

VERTEX_AI_PREFIX = "vertex_ai/"

MODEL_GEMINI_2_5_PRO = f"{VERTEX_AI_PREFIX}gemini-2.5-pro"
MODEL_GEMINI_2_5_FLASH = f"{VERTEX_AI_PREFIX}gemini-2.5-flash"


AVAILABLE_AA_MODELS = [
    MODEL_GEMMA,
    MODEL_LLAMA,
    MODEL_GPT_OSS_120B,
    MODEL_QWEN3_30B_A3B_THINKING_2507_FP8,
    MODEL_QWEN3_235B_A22B_THINKING_2507_FP8,
]
AVAILABLE_VERTEX_AI_MODELS = [MODEL_GEMINI_2_5_PRO, MODEL_GEMINI_2_5_FLASH]

DEFAULT_MODEL_QUERY_AGENT = MODEL_GEMINI_2_5_PRO
DEFAULT_MODEL_DATA_ANALYSIS_AGENT = MODEL_GEMINI_2_5_PRO
DEFAULT_MODEL_LLM_COMPLETION = MODEL_GEMINI_2_5_PRO
DEFAULT_MODEL_EVAL = MODEL_QWEN3_30B_A3B_THINKING_2507_FP8
DEFAULT_MODEL_EXPLAINABILITY = MODEL_GEMINI_2_5_FLASH
DEFAULT_MODEL_WEAK = MODEL_GEMINI_2_5_FLASH
