[project]
name = "eu-law"
version = "0.1.0"
description = "Playground to wrangle EU legal act data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "jupyter>=1.1.1",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "rdflib>=7.1.4",
]
