# IMPORTANT:
# - Ensure that you have added the necessary GitHub variables and secrets in your repository settings.
# - The following variables and secrets must be configured:
#     • SERVICE_AUTHENTICATION_TOKEN with PhariaOS Permissions
#     • PHARIAOS_MANAGER_URL
#     • IMAGE_REGISTRY
#     • IMAGE_REPOSITORY
#     • IMAGE_REGISTRY_USER
#     • IMAGE_REGISTRY_PASSWORD
#     • ALEPH_ALPHA_OCI_REGISTRY_USER
#     • ALEPH_ALPHA_OCI_REGISTRY_ACCESS_TOKEN
#
# - For Kernel based applications, also configure:
#     • SERVICE_PHARIA_KERNEL_URL

# - For applications using PhariaData, also configure:
#     • SERVICE_PHARIA_DATA_URL
#
# - For Summary based applications, also configure:
#     • SERVICE_PHARIA_AI_INFERENCE_API_BASE_URL
#     • SERVICE_SUMMARY_MODEL

# - Additionally, replace <application-name> in the deploy and publish commands with your actual application name.

name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  test_ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        env:
            ALEPH_ALPHA_OCI_REGISTRY_USER: ${{ secrets.ALEPH_ALPHA_OCI_REGISTRY_USER }}
            ALEPH_ALPHA_OCI_REGISTRY_ACCESS_TOKEN: ${{ secrets.ALEPH_ALPHA_OCI_REGISTRY_ACCESS_TOKEN }}
        run: pnpm install

      - name: Run tests
        run: pnpm test:unit

  test_service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install uv
        uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b # pinned to commit of v6.6.0

      - name: Install dependencies
        run: uv sync --dev

      - name: Run service tests
        run: uv run pytest

  deploy:
    needs: [test_ui, test_service]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Configure npm registry for @aleph-alpha
        run: |
          npm config set @aleph-alpha:registry=https://alephalpha.jfrog.io/artifactory/api/npm/assistant-npm/
          npm config set //alephalpha.jfrog.io/artifactory/api/npm/assistant-npm/:_authToken=${{ secrets.ALEPH_ALPHA_OCI_REGISTRY_ACCESS_TOKEN }}

      - name: Publish and Deploy Application
        env:
          SERVICE_AUTHENTICATION_TOKEN: ${{ secrets.SERVICE_AUTHENTICATION_TOKEN }}
          PHARIAOS_MANAGER_URL: ${{ vars.PHARIAOS_MANAGER_URL }}
          IMAGE_REGISTRY: ${{ secrets.IMAGE_REGISTRY }}
          IMAGE_REPOSITORY: ${{ secrets.IMAGE_REPOSITORY }}
          IMAGE_REGISTRY_USER: ${{ secrets.IMAGE_REGISTRY_USER }}
          IMAGE_REGISTRY_PASSWORD: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}

          # For Kernel based applications
          SERVICE_PHARIA_KERNEL_URL: ${{ vars.PHARIA_KERNEL_URL }}

          # For applications using PhariaData
          SERVICE_PHARIA_DATA_URL: ${{ vars.PHARIA_DATA_URL }}

          # For Summary Based Applications
          SERVICE_PHARIA_AI_INFERENCE_API_BASE_URL: ${{ vars.PHARIA_AI_INFERENCE_API_BASE_URL }}
          SERVICE_SUMMARY_MODEL: ${{ vars.SUMMARY_MODEL }}
        run: |
          npx @aleph-alpha/pharia-ai-cli deploy --image <application-name>
          npx @aleph-alpha/pharia-ai-cli publish --name <application-name>
